# Generated by Django 4.1.6 on 2023-04-18 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_way', '0002_email_email_email_sno'),
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNO', models.TextField()),
                ('EMAIL', models.EmailField(max_length=254)),
            ],
        ),
    ]
