# Generated by Django 4.1.6 on 2023-05-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_way', '0005_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='contact',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='services',
            name='mail',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_required_on',
            field=models.TextField(),
        ),
    ]
