# Generated by Django 4.1.7 on 2023-05-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_way', '0006_alter_services_contact_alter_services_mail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='service_for',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
