# Generated by Django 4.1.7 on 2023-05-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_way', '0007_services_service_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='signup',
            name='username',
            field=models.TextField(max_length=100),
        ),
    ]
