# Generated by Django 4.1.7 on 2023-05-09 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('New_way', '0008_alter_signup_email_alter_signup_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring',
            name='password',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='contactno',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='experience',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='jobrole',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='location',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='mail',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='qualification',
            field=models.TextField(max_length=1000),
        ),
    ]
